apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
      - name: payments-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
